# ----------------------------
# Makefile Options
# ----------------------------

NAME = CANVAS
ICON = icon.png
DESCRIPTION = "Color canvas with RGB dithering"
COMPRESSED = NO
ARCHIVED = NO
OUTPUT_MAP = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
